name: Pipeline (extract persons + build site index)

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # nightly at 02:00 UTC (optional)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add what your script needs:
          # pip install -r requirements.txt
          # Example placeholders:
          # pip install google-genai google-auth
          true

      - name: Run pipeline
        env:
          # Put your secrets in GitHub repo settings:
          # Settings -> Secrets and variables -> Actions -> New repository secret
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # or GOOGLE_APPLICATION_CREDENTIALS_JSON if you use service accounts, etc.
        run: |
          python scripts/run_pipeline.py --genai-metadata

      - name: Commit generated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output bib site/index.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update extracted outputs"
            git push
          fi
