name: Pipeline (extract persons + build site data)

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # nightly (optional)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # PDF text extraction:
          pip install pypdf
          # Add whatever your extractor uses (example):
          # pip install google-genai google-auth
          # or:
          # pip install -r requirements.txt

      - name: Run pipeline
        env:
          # Put your secrets in:
          # Settings -> Secrets and variables -> Actions
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python scripts/run_pipeline.py --genai-metadata

      - name: Commit generated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # We commit the data the site needs:
          git add site/index.json site/data site/bib bib

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update extracted site data"
            git push
          fi
